### PR TITLE
Enable avatars on rooms and users

### PR DESCRIPTION
**Pull request by AlmAck**
This code introduces the avatar on both rooms and users in the qml code.
The AvatarImage.qml code is responsable to take the avatar, resize and create a circle image as result.

ToDo:
- on ChatRoom2.qml use the avatar when available and fallback to the color bubble when not available
- on RoomsPage.qml introduce color bubbles? as done in ChatRoom2?
- add some left padding the the image on the RoomsPage.qml

### CODE REVIEW

**Comment by r0kk3rz** [comment]
Yeah we might need to do some checks in the model to make sure that the user has an avatar and return null or empty string so we can pick it out.

at the moment it floods the debug with messages about not being able to find an image. but for now this looks good

**Comment by Sailbook** [comment]
@AlmAck, i know it's not complete and there are still some TODO's but i try to compile it now and i get this 2 error:

/home/rudi/Development/harbour-matrix/src/models/roomlistmodel.cpp:82: error: 'class QMatrixClient::Room' has no member named 'avatarUrl'
         return QUrl("image://mxc/" + room->avatarUrl().host() + room->avatarUrl().path());
                                            ^
/home/rudi/Development/harbour-matrix/src/models/roomlistmodel.cpp:82: error: 'class QMatrixClient::Room' has no member named 'avatarUrl'
         return QUrl("image://mxc/" + room->avatarUrl().host() + room->avatarUrl().path());
                                                                       ^

**Comment by r0kk3rz** [comment]
Yes it seems there is no way to get the avatarUrl out of the room object in the library, so that part will have to be removed.

Also remove the modelimageprovider class as we already have a working one

**Comment by Sailbook** [comment]
So if i understand this part need to removed?

+    if(role == AvatarRole)
+    {
+        User *user = m_connection->user(event->senderId());
+        return QUrl("image://mxc/" + user->avatarUrl().host() + user->avatarUrl().path());
+    }

**Pull request merged**
